Repository DLL-S/ueg-construcao-software, pull requests merged in 2021-01, with the labels that each got.

#10 Prototipos de tela
  .gitignore
  1_Descrição do problema - Auto Peças.docx
  2 - Prototipos/Baixa fidelidade/F1 - Alterar produto.html
  2 - Prototipos/Baixa fidelidade/F1 - Cadastrar produto.html
  2 - Prototipos/Baixa fidelidade/F1 - Inativar produto.html
  2 - Prototipos/Baixa fidelidade/F2 - Alterar funcionario.html
  2 - Prototipos/Baixa fidelidade/F2 - Cadastrar funcionario.html
  2 - Prototipos/Baixa fidelidade/F2 - Inativar funcionário.html
  2 - Prototipos/Baixa fidelidade/F3 - Alterar cliente.html
  2 - Prototipos/Baixa fidelidade/F3 - Cadastrar cliente.html
  2 - Prototipos/Baixa fidelidade/F5 - Alterar marca.html
  2 - Prototipos/Baixa fidelidade/F5 - Cadastrar marca.html
  2 - Prototipos/Baixa fidelidade/F5 - Inativar marca.html
  2 - Prototipos/Baixa fidelidade/F7 - Manter venda.html
  2 - Prototipos/Baixa fidelidade/Imagens/F1 - Alterar produto.png
  2 - Prototipos/Baixa fidelidade/Imagens/F1 - Cadastrar produto.png
  2 - Prototipos/Baixa fidelidade/Imagens/F1 - Inativar produto.png
  2 - Prototipos/Baixa fidelidade/Imagens/F2 - Alterar funcionario.png
  2 - Prototipos/Baixa fidelidade/Imagens/F2 - Cadastrar funcionario.png
  2 - Prototipos/Baixa fidelidade/Imagens/F2 - Inativar funcionário.png
  2 - Prototipos/Baixa fidelidade/Imagens/F3 - Alterar cliente.png
  2 - Prototipos/Baixa fidelidade/Imagens/F3 - Cadastrar cliente.png
  2 - Prototipos/Baixa fidelidade/Imagens/F5 - Alterar marca.png
  2 - Prototipos/Baixa fidelidade/Imagens/F5 - Cadastrar marca.png
  2 - Prototipos/Baixa fidelidade/Imagens/F5 - Inativar marca.png
  2 - Prototipos/Baixa fidelidade/Imagens/F7 - Manter venda.png
  2 - Prototipos/Peça Certa - Efetivar venda.png
  2 - Prototipos/Peça Certa - Estoque.png
  2 - Prototipos/Peça Certa - Home.png
  2 - Prototipos/Peça Certa - Login.png
  2 - Prototipos/Peça Certa - Manter categorias.png
  2 - Prototipos/Peça Certa - Manter funcionários.png
  2 - Prototipos/Peça Certa - Manter marcas.png
  2 - Prototipos/Peça Certa - Manter produtos.png
  2 - Prototipos/Peça Certa - Pesquisar compras.png
  2 - Prototipos/Peça Certa - Pesquisar orçamentos.png
  2 - Prototipos/Peça Certa - Pesquisar vendas.png
  2 - Prototipos/Peça Certa - Pré-venda.png
  2 - Prototipos/Peça Certa.png
  2 - Prototipos/logo.png
Labels: documentation, project, requirements

#11 Lista de requisitos
  1 - Listagem de requisitos/Requisitos.md
Labels: documentation, enhancement, project, requirements

#14 Diagrama de classes
  CONTRIBUTING.md
  Modelagem e requisitos/Diagrama de classes/Diagrama de classes - PeçaCerta.asta
  Modelagem e requisitos/Diagrama de classes/Diagrama de classes - PeçaCerta.asta.lock
  Modelagem e requisitos/Prototipos/Peça Certa - Manter funcionários.png
Labels: documentation, project, requirements

#20 Base para o backend
  Backend/.gitignore
  Backend/pecacerta-api/.gitignore
  Backend/pecacerta-api/.mvn/wrapper/MavenWrapperDownloader.java
  Backend/pecacerta-api/.mvn/wrapper/maven-wrapper.jar
  Backend/pecacerta-api/.mvn/wrapper/maven-wrapper.properties
  Backend/pecacerta-api/mvnw
  Backend/pecacerta-api/mvnw.cmd
  Backend/pecacerta-api/pom.xml
  Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/PecacertaApiApplication.java
  Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/model/Endereco.java
  Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/model/Funcionario.java
  Backend/pecacerta-api/src/main/resources/application.properties
  Backend/pecacerta-api/src/main/resources/db/migration/V01__CRIA_E_REGISTRA_CATEGORIAS.sql
  Backend/pecacerta-api/src/test/java/com/dlls/pecacerta/api/PecacertaApiApplicationTests.java
Labels: development, project, requirements

#32 Atualiza diagrama de classes: Entidade Usuario
  Modelagem e requisitos/Diagrama de classes/Diagrama de classes - PeçaCerta.asta
  Modelagem e requisitos/Diagrama de classes/Diagrama de classes - PeçaCerta.png
Labels: documentation, enhancement, project, requirements

#27 Backend cliente
  Backend/pecacerta-api/pom.xml
  Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/controllers/ClienteController.java
  Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/events/ResourceCreatedEvent.java
  Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/events/listener/ResourceCreatedListener.java
  Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/exceptions/ClienteAlreadyExistsException.java
  Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/exceptions/ClienteNoneExistentException.java
  Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/exceptions/PecaCertaExceptionHandler.java
  Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/model/Cliente.java
  Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/repositories/ClienteRepository.java
  Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/services/ClienteService.java
  Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/utils/EnumTipoCliente.java
  Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/utils/Error.java
  Backend/pecacerta-api/src/main/resources/application.properties
  Backend/pecacerta-api/src/main/resources/db/migration/V03__CREATE_CLIENTES.sql
Labels: development

#28 Backend funcionario
  Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/controllers/FuncionarioController.java
  Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/events/ResourceCreatedEvent.java
  Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/events/listener/ResourceCreatedListener.java
  Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/exceptions/FuncionarioAlreadyExistsException.java
  Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/exceptions/FuncionarioNonexistentException.java
  Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/exceptions/PecaCertaExceptionHandler.java
  Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/model/Funcionario.java
  Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/repositories/FuncionarioRepository.java
  Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/services/FuncionarioService.java
  Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/utils/Error.java
  Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/utils/TipoFuncionario.java
  Backend/pecacerta-api/src/main/resources/ValidationMessages.properties
  Backend/pecacerta-api/src/main/resources/db/migration/V02__CRIA_E_REGISTRA_FUNCIONARIOS.sql
  Backend/pecacerta-api/src/main/resources/messages.properties
  Modelagem e requisitos/Diagrama de classes/Diagrama de classes - PeçaCerta.png
Labels: development

#29 Backend produto
  Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/controllers/CategoriaController.java
  Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/controllers/MarcaController.java
  Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/controllers/ProdutoController.java
  Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/exceptions/ResourceNotFoundException.java
  Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/model/Categoria.java
  Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/model/Marca.java
  Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/model/Produto.java
  Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/repositories/CategoriaRepository.java
  Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/repositories/MarcaRepository.java
  Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/repositories/ProdutoRepository.java
  Backend/pecacerta-api/src/main/resources/db/migration/V01__CRIA_E_REGISTRA_CATEGORIAS.sql
  Backend/pecacerta-api/src/main/resources/db/migration/V01__CRIA_TABELA_CATEGORIAS.sql
  Backend/pecacerta-api/src/main/resources/db/migration/V04__CRIA_TABELA_MARCAS.sql
  Backend/pecacerta-api/src/main/resources/db/migration/V05__CRIA_TABELA_PRODUTOS.sql
  Modelagem e requisitos/Diagrama de classes/Diagrama de classes - PeçaCerta.png
Labels: development

#35 Inclusão dos filtros de Pesquisa (Classe produtoController)
  Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/controllers/CategoriaController.java
  Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/controllers/ProdutoController.java
  Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/model/Categoria.java
  Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/model/Marca.java
  Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/repositories/CategoriaRepository.java
  Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/repositories/MarcaRepository.java
  Backend/pecacerta-api/src/main/java/com/dlls/pecacerta/api/repositories/ProdutoRepository.java
Labels: development
